name: Run CakePHP CodeSniffer

runs:
  using: composite

  steps:
    - name: Install CodeSniffer
      run: composer require --dev cakephp/cakephp-codesniffer
      shell: bash

    - name: Run PHP CodeSniffer
      run: composer cs-check
      shell: bash
