name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

permissions:
  contents: read

defaults:
  run:
    working-directory: ./backend

jobs:
  php--testsuite:
    name: PHPUnit
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/php/setup
      - uses: ./.github/actions/php/run-phpunit

  php--coding-standard:
    name: Coding Standard
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/php/setup
      - uses: ./.github/actions/php/run-cakephp-code-sniffer

  php--ide-helper:
    name: Ide Helper
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: ide-helper-demo
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/php/setup
      - uses: ./.github/actions/php/run-cakephp-ide-helper
